# Generated by Django 5.0.4 on 2024-04-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('price', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['-price'],
                'indexes': [models.Index(fields=['-price'], name='fertzmall_s_price_be87d3_idx')],
            },
        ),
    ]
